Base:
    model_root: './checkpoints/'
    num_workers: 8
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

EKTF_Criteo: # This is a config template
    model: EKTF
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_student: 3
    hidden_units: [400, 400, 400]
    hidden_activations: relu
    net_dropout: 0.1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

EKTF_L_Criteo: # This is a config template
    model: EKTF_L
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    hidden_units: [400, 400, 400]
    hidden_activations: relu
    net1_dropout: 0.1
    net2_dropout: 0.2
    net3_dropout: 0.1
    num_cross_layers: 4
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'